apiVersion: v1
kind: Service
metadata:
  name: onboarding-app-fe-service
spec:
  selector:
    app: onboarding-app-fe
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
