apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-app-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onboarding-app-fe
  template:
    metadata:
      labels:
        app: onboarding-app-fe
    spec:
      containers:
      - name: onboarding-app-fe
        image: hungndacr.azurecr.io/my-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_BASE_URL
          value: "https://52-246-136-171.sslip.io/api"
