apiVersion: v1
kind: Service
metadata:
  name: onboarding-app-be-service
spec:
  selector:
    app: onboarding-app-be
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
