apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onboarding-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - 52-246-136-171.sslip.io
      secretName: onboarding-app-tls
  rules:
    - host: 52-246-136-171.sslip.io
      http:
        paths:
          # Backend API
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: onboarding-app-be-service
                port:
                  number: 80
          # Frontend React SPA
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: onboarding-app-fe-service
                port:
                  number: 80
